### ISSUE TITLE
workflows fail in github, but not on local computer

### ISSUE THREAD

**Issue by msupernaw** [nmfs-fish-tools/r4MAS#65]

**Comment by Bai-Li-NOAA** [comment]
The workflows fail when running `remotes::dev_package_deps(dependencies = TRUE)`. The error message is:
`
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/cstawitz/jsonlite/contents/DESCRIPTION?ref=HEAD'
Calls: saveRDS ... github_DESCRIPTION -> download -> base_download -> base_download_headers
Execution halted
`
I tried to remove cstawitz/jsonlite from DESCRIPTION, but the workflow still tried to install cstawitz/jsonlite and failed.

**Comment by Bai-Li-NOAA** [comment]
The issue is similar to this issue: https://github.com/r-lib/remotes/issues/130. I didn't try a different download method in the GitHub Actions workflow as suggested. I changed cstawitz/jsonlite to jeroen/jsonlite in the DESCRIPTION file. I got the error below:
`
Error in utils::download.file(url, path, method = method, quiet = quiet, : cannot open URL 'https://api.github.com/repos/cstawitz/jsonlite/contents/DESCRIPTION?ref=HEAD'
`

Then I totally removed jsonlite from the DESCRIPTION file. The R-CMD-CHECK workflow works now and the new error is about r4MAS memory mapping:
`
 *** caught segfault ***
address 0x0, cause 'memory not mapped'
`

**Comment by k-doering-NOAA** [comment]
@Bai-Li-NOAA, Kelli figured out how to fix this, by adding in this line: 
https://github.com/nmfs-fish-tools/SSMSE/blob/main/.github/workflows/r-cmd-check.yml#L30

See if that works for you? It worked for us for 3 repos

**Comment by Bai-Li-NOAA** [comment]
@k-doering-NOAA Thanks, it works for us as well!

**Comment by Bai-Li-NOAA** [comment]
Hi @msupernaw, the GitHub actions jsonlite installation error has been resolved, but we still got a few errors when running R-CMD-check workflow. Please see the details [here](https://github.com/nmfs-fish-tools/r4MAS/actions/runs/1136076626). The errors are different for different OS.

I can update the workflow and let it run checks on every new commit again.
